### create users
POST http://192.168.18.155:8000/user/create
Content-Type: application/json

{
    "email": "fgilng224@gmail.com",
    "password": "131313"
}

### login users
POST  http://192.168.18.155:8000/user/login
Content-Type: application/json

{
    "email": "fgilang224@gmail.com",
    "password": "131313"
}

### read users
GET http://192.168.18.155:8000/user/read
Content-Type: application/json

### create notes
POST http://192.168.18.155:8000/notes/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJmZ2lsbmcyMjRAZ21haWwuY29tIiwiaWF0IjoxNjczNzE5NjE4fQ.BsPVLH6KXiVo-Z3t-KLtyZcy-H2V-1nB-47yquY65cQ

{
    "title": "ini title pertama",
    "notes": "ini notes pertama"
}

### read notes
GET http://192.168.18.155:8000/notes/read
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJmZ2lsbmcyMjRAZ21haWwuY29tIiwiaWF0IjoxNjczNzE5NjE4fQ.BsPVLH6KXiVo-Z3t-KLtyZcy-H2V-1nB-47yquY65cQ

### update notes
PUT http://192.168.18.155:8000/notes/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJmZ2lsbmcyMjRAZ21haWwuY29tIiwiaWF0IjoxNjczNzE5NjE4fQ.BsPVLH6KXiVo-Z3t-KLtyZcy-H2V-1nB-47yquY65cQ

{
    "title": "ini tile diu",
    "notes": "ini note diu"
}

### delete notes
DELETE http://192.168.18.155:8000/notes/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJmZ2lsbmcyMjRAZ21haWwuY29tIiwiaWF0IjoxNjczNzE5NjE4fQ.BsPVLH6KXiVo-Z3t-KLtyZcy-H2V-1nB-47yquY65cQ
